//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "coordinates")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub pid: Uuid,
    pub name: String,
    pub description: Option<String>,
    pub occasion: Option<String>,
    pub season: Option<String>,
    pub style: Option<String>,
    pub user_id: i32,
    pub is_favorite: bool,
    pub image_url: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::clothes_coordinates::Entity")]
    ClothesCoordinates,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id"
    )]
    Users,
}

impl Related<super::clothes::Entity> for Entity {
    fn to() -> RelationDef {
        super::clothes_coordinates::Relation::Clothes.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::clothes_coordinates::Relation::Coordinates.def().rev())
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::clothes_coordinates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ClothesCoordinates.def()
    }
}


