//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0
pub use super::users::Entity as Users;
pub use super::clothes::Entity as Clothes;
pub use super::coordinates::Entity as Coordinates;
pub use super::clothes_coordinates::Entity as ClothesCoordinates;
