//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

pub use super::clothes::Entity as Clothes;
pub use super::clothes_coordinates::Entity as ClothesCoordinates;
pub use super::coordinates::Entity as Coordinates;
pub use super::passkeys::Entity as Passkeys;
pub use super::users::Entity as Users;
pub use super::webauthn_sessions::Entity as WebauthnSessions;
